use_frameworks!

target 'GNRAlertController_Example' do
  pod 'GNRAlertController', :path => '../'

  target 'GNRAlertController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
